cf.client.secret=${CF_CLIENT_SECRET:missing_client_secret}
cf.client.id=${CF_CLIENT_ID:missing_client_id}
discord.bot.token=${DISCORD_TOKEN:missing_token}
crehft.url=crehft.propersi.app
server.port=9980

logging.file.path=/app/logs
logging.file.name=/app/logs/rehplacer.log
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.total-size-cap=100MB
logging.logback.rollingpolicy.max-history=7
